// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHXzWJZ_ZmIjSP7DVB6gJcbmSWlTn8cRc',
    appId: '1:916756813662:web:4196cb04d11e45077261cf',
    messagingSenderId: '916756813662',
    projectId: 'unchi-cricket',
    authDomain: 'unchi-cricket.firebaseapp.com',
    storageBucket: 'unchi-cricket.firebasestorage.app',
    measurementId: 'G-MDR0XP8ZMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcKtEDWNP4u82_alCmXgTHmX1-u5QQpNo',
    appId: '1:916756813662:android:7dfb40099b0dc7bb7261cf',
    messagingSenderId: '916756813662',
    projectId: 'unchi-cricket',
    storageBucket: 'unchi-cricket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEUvb381nPwDXJ4HQpRhacGSYv5B-8BLc',
    appId: '1:916756813662:ios:344b1db2dacc74d67261cf',
    messagingSenderId: '916756813662',
    projectId: 'unchi-cricket',
    storageBucket: 'unchi-cricket.firebasestorage.app',
    iosBundleId: 'com.example.unchiCricket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEUvb381nPwDXJ4HQpRhacGSYv5B-8BLc',
    appId: '1:916756813662:ios:344b1db2dacc74d67261cf',
    messagingSenderId: '916756813662',
    projectId: 'unchi-cricket',
    storageBucket: 'unchi-cricket.firebasestorage.app',
    iosBundleId: 'com.example.unchiCricket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHXzWJZ_ZmIjSP7DVB6gJcbmSWlTn8cRc',
    appId: '1:916756813662:web:725168f1a0ce435c7261cf',
    messagingSenderId: '916756813662',
    projectId: 'unchi-cricket',
    authDomain: 'unchi-cricket.firebaseapp.com',
    storageBucket: 'unchi-cricket.firebasestorage.app',
    measurementId: 'G-GDHT2VC35F',
  );
}
